# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
