# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-22 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180622_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
