# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('modelYear', models.CharField(max_length=30)),
                ('engineCylinders', models.CharField(max_length=30)),
                ('transmissionStyle', models.CharField(max_length=30)),
                ('trim', models.CharField(max_length=30)),
            ],
        ),
    ]
