# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(max_length=30, verbose_name='Vin Number'),
        ),
    ]
