# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180621_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='engineCylinders',
            field=models.CharField(max_length=30, verbose_name='Engine Cylinders'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='modelYear',
            field=models.CharField(max_length=30, verbose_name='Model Year'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmissionStyle',
            field=models.CharField(max_length=30, verbose_name='Transmission Style'),
        ),
    ]
